// ── ToolsRift Network — active site resolver ─────────────────────────────────
// ONE codebase, THIRTY build targets:
//
//   NEXT_PUBLIC_SITE_ID unset / "hub"  →  toolsrift.com, exactly as before
//   NEXT_PUBLIC_SITE_ID=pdf            →  pdf.toolsrift.com  (standalone site)
//   NEXT_PUBLIC_SITE_ID=json           →  json.toolsrift.com (slug also accepted)
//   …one per entry in lib/sites/brands.js
//
// The variable is read at BUILD time (Next.js inlines NEXT_PUBLIC_* into every
// bundle, middleware included), so each Vercel project builds a site that only
// knows about itself: its own domain, brand, tool set, sitemap, manifest and
// Android app identity. Every other category is reached through the network
// links (see categoryHome / toolPath below).
//
// Import `SITE` anywhere — server, client, middleware, API routes, scripts.

const { BRANDS, findBrand } = require('./brands');

const HUB_DOMAIN = 'toolsrift.com';
const HUB_BASE = `https://${HUB_DOMAIN}`;

const RAW_ID = process.env.NEXT_PUBLIC_SITE_ID || '';
const brand = RAW_ID && RAW_ID !== 'hub' ? findBrand(RAW_ID) : null;

if (RAW_ID && RAW_ID !== 'hub' && !brand) {
  // Fail loudly at build time instead of silently shipping the hub under the
  // wrong domain.
  throw new Error(
    `[toolsrift] Unknown NEXT_PUBLIC_SITE_ID="${RAW_ID}". ` +
    `Use "hub" or one of: ${BRANDS.map(b => b.id).join(', ')}`
  );
}

const SITE = brand
  ? {
      kind: 'category',
      isStandalone: true,
      id: brand.id,
      slug: brand.slug,
      brand,
      domain: brand.domain,
      baseUrl: `https://${brand.domain}`,
      siteName: brand.siteName,
      tagline: brand.tagline,
      hubUrl: HUB_BASE,
      // Static assets generated by scripts/generate-brand-assets.js
      logo: `/brands/${brand.id}/logo.svg`,
      logoDark: `/brands/${brand.id}/logo.svg`,
      icon: `/brands/${brand.id}/icon.svg`,
      icon192: `/brands/${brand.id}/icon-192.png`,
      icon512: `/brands/${brand.id}/icon-512.png`,
      ogImage: `/brands/${brand.id}/og.png`,
      themeColor: brand.palette.primary,
      bgColor: brand.palette.bg,
    }
  : {
      kind: 'hub',
      isStandalone: false,
      id: 'hub',
      slug: null,
      brand: null,
      domain: HUB_DOMAIN,
      baseUrl: HUB_BASE,
      siteName: 'ToolsRift',
      tagline: 'Free online tools, no signup',
      hubUrl: HUB_BASE,
      logo: '/logo.svg',
      logoDark: '/logo.svg',
      icon: '/icon.svg',
      icon192: '/icon-192.png',
      icon512: '/icon-512.png',
      ogImage: '/og-image.png',
      themeColor: '#3B82F6',
      bgColor: '#06090F',
    };

/** All standalone sites — the "ToolsRift network" (for footers, cross-links, scripts). */
const NETWORK = BRANDS.map(b => ({
  id: b.id,
  slug: b.slug,
  domain: b.domain,
  siteName: b.siteName,
  live: !!b.live,
  url: b.live ? `https://${b.domain}/` : `${HUB_BASE}/${b.slug}`,
}));

/**
 * Home URL of a category, from the point of view of the CURRENT site.
 *   hub          → "https://pdf.toolsrift.com/"  (live brand: the hub 301s /pdf there)
 *   hub          → "/pdf"                        (brand not live yet: hub serves it)
 *   pdf site     → "/"                           (its own home)
 *   pdf site     → "https://image.toolsrift.com/"  (sibling, if that brand is live)
 *   pdf site     → "https://toolsrift.com/images" (sibling not yet live → hub)
 */
function categoryHome(idOrSlug) {
  const b = findBrand(idOrSlug);
  if (!b) return SITE.isStandalone ? `${HUB_BASE}/` : '/';
  if (SITE.isStandalone && b.id === SITE.id) return '/';
  if (b.live) return `https://${b.domain}/`;
  return SITE.isStandalone ? `${HUB_BASE}/${b.slug}` : `/${b.slug}`;
}

/** Join a base route and a tool id without producing "//" or "/pdf//x". */
function joinRoute(base, toolId) {
  if (!toolId) return base;
  if (!base || base === '/') return `/${toolId}`;
  return base.endsWith('/') ? `${base}${toolId}` : `${base}/${toolId}`;
}

/** URL of a tool page, from the point of view of the CURRENT site. */
function toolPath(idOrSlug, toolId) {
  return joinRoute(categoryHome(idOrSlug), toolId);
}

/** Absolute URL on the current site. */
function absoluteUrl(path = '/') {
  const p = path.startsWith('/') ? path : `/${path}`;
  return `${SITE.baseUrl}${p === '/' ? '' : p}` || SITE.baseUrl;
}

/** Paths a standalone site serves itself (everything else 301s to the hub). */
const STANDALONE_SHARED_PAGES = [
  '/about', '/contact', '/privacy-policy', '/terms', '/cookies', '/disclaimer', '/404',
];

module.exports = {
  SITE,
  NETWORK,
  BRANDS,
  HUB_DOMAIN,
  HUB_BASE,
  STANDALONE_SHARED_PAGES,
  findBrand,
  categoryHome,
  toolPath,
  joinRoute,
  absoluteUrl,
};
