// ── ToolsRift per-tool icon overrides ────────────────────────────────────────
// Icons are authored inline in each components/toolsrift-*.jsx TOOLS array, but
// many categories reuse one emoji across most of their tools (PDF used 📄 on 17
// of 28). Entries here win over the inline icon, so a category can be de-duped
// without editing hundreds of inline tool objects.
//
// Only add an id when the inline icon collides with a sibling. Categories whose
// inline icons are already distinct (js, encoding, colors, converters2, fancy,
// gen-security, units, gen-devconfig, gen-content) need no entries.

export const TOOL_ICONS = {
  // ── PDF ───────────────────────────────────────────────────────────────────
  // view
  'pdf-viewer':            '👁️',
  'pdf-page-count':        '🔢',
  'pdf-metadata':          '🏷️',
  'pdf-text-extractor':    '📝',
  // edit
  'pdf-merger':            '🔗',
  'pdf-splitter':          '✂️',
  'pdf-page-extractor':    '📑',
  'pdf-rotator':           '🔄',
  'pdf-reorder':           '↕️',
  'pdf-delete-pages':      '🗑️',
  // convert
  'pdf-to-jpg':            '🖼️',
  'pdf-to-png':            '🌄',
  'jpg-to-pdf':            '📥',
  'png-to-pdf':            '📤',
  'pdf-to-text':           '📃',
  'word-to-pdf':           '📘',
  // security
  'pdf-password-protect':  '🔒',
  'pdf-unlock':            '🔓',
  'pdf-watermark':         '💧',
  'pdf-redact':            '⬛',
  // optimize
  'pdf-compressor':        '🗜️',
  'pdf-optimizer':         '⚡',
  'pdf-metadata-editor':   '✏️',
  // tools
  'pdf-page-numbering':    '#️⃣',
  'pdf-margin-adder':      '📐',
  'pdf-cropper':           '🔲',
  'pdf-bookmarks':         '🔖',
  'pdf-form-filler':       '🖊️',
  // data & ai
  'pdf-to-markdown':       '✍️',
  'pdf-to-json':           '🧾',
  'pdf-table-extractor':   '📊',
  'pdf-chunker':           '🧩',

  // ── JSON (was 🧬 on 21 of 25) ──────────────────────────────────────────────
  'json-minifier':    '🗜️',
  'json-escape':      '🔤',
  'json-size':        '📏',
  'json-to-csv':      '📊',
  'csv-to-json':      '📥',
  'json-to-xml':      '📰',
  'xml-to-json':      '📤',
  'json-to-yaml':     '📜',
  'yaml-to-json':     '📄',
  'json-to-markdown': '📝',
  'json-to-env':      '🔑',
  'json-diff':        '🔀',
  'json-path':        '🛣️',
  'json-schema':      '✅',
  'json-sorter':      '↕️',
  'json-flatten':     '⬇️',
  'json-unflatten':   '⬆️',
  'json-keys':        '🗝️',
  'json-merger':      '🔗',
  'json-array-tools': '📚',
  'json-query':       '🔍',

  // ── Images (was 🖼️ on 20 of 50) ────────────────────────────────────────────
  'image-resizer':         '📐',
  'image-cropper':         '✂️',
  'image-rotator':         '🔃',
  'image-flipper':         '🪞',
  'image-thumbnail':       '🖼️',
  'image-brightness':      '☀️',
  'image-blur':            '🌫️',
  'image-sharpen':         '🔪',
  'image-invert':          '🌗',
  'image-pixelate':        '🟪',
  'image-vignette':        '⭕',
  'image-watermark':       '💧',
  'image-text-overlay':    '🔤',
  'image-caption':         '💬',
  'image-border':          '🔲',
  'image-logo':            '🏷️',
  'image-color-picker':    '🎨',
  'image-dominant-colors': '🌈',
  'image-metadata':        '📋',
  'image-info':            'ℹ️',
  'image-histogram':       '📊',
  'placeholder-image':     '🟦',
  'noise-texture':         '📺',
  'favicon-generator':     '🔖',
  'og-image-preview':      '👁️',
  'avatar-generator':      '👤',
  'image-base64':          '🔢',
  'base64-to-image':       '🔡',
  'svg-to-png':            '🖌️',
  'image-to-svg':          '✒️',
  'sprite-sheet':          '🎞️',
  'image-collage':         '🧩',
  'pdf-to-image':          '📄',
  'image-to-pdf':          '📕',
  'screenshot-taker':      '📸',
  'dpi-checker':           '🔬',
  'color-space':           '🎭',

  // ── Encoders (was 🔢 on 7, 📄 on 3, 🔐 on 3) ───────────────────────────────
  'base64-encode':   '📦',
  'base64-decode':   '📭',
  'base64-image':    '🖼️',
  'base32-encode':   '🔢',
  'base32-decode':   '🔡',
  'url-encode':      '🔗',
  'url-decode':      '⛓️',
  'html-encode':     '📄',
  'html-decode':     '📃',
  'binary-encode':   '1️⃣',
  'binary-decode':   '0️⃣',
  'hex-encode':      '#️⃣',
  'octal-encode':    '🎱',
  'unicode-decode':  '🔣',
  'unicode-lookup':  '🔤',
  'jwt-decoder':     '🎟️',
  'caesar-cipher':   '🏛️',
  'vigenere-cipher': '🗝️',
  'morse-encoder':   '📡',
  'xml-encode':      '📰',

  // ── Hash & Crypto (was #️⃣ on 7) ───────────────────────────────────────────
  'hash-all':           '🧮',
  'md5-hash':           '5️⃣',
  'sha384-hash':        '🔐',
  'hmac-generator':     '🔏',
  'hash-compare':       '⚖️',
  'crc32':              '🔁',
  'adler32':            '✅',
  'fnv-hash':           '🧬',
  'password-generator': '🔑',
  'passphrase-gen':     '📝',
  'password-strength':  '💪',
  'hash-file':          '📁',
  'caesar-hash':        '🔤',

  // ── Dev Tools (was ⏱️ on 5, 🌐 on 3) ───────────────────────────────────────
  'unix-timestamp':     '⏱️',
  'cron-parser':        '📅',
  'cron-gen':           '🗓️',
  'timezone-dev':       '🌍',
  'crontab-guru':       '⏰',
  'url-parser':         '🔗',
  'ip-info':            '📍',
  'cidr-calc':          '🧮',
  'http-status-codes':  '🚦',
  'http-headers-ref':   '📋',
  'curl-builder':       '💻',
  'curl-to-code':       '🔁',
  'html-entities-ref':  '🧱',
  'css-units-ref':      '📏',
  'regex-cheatsheet':   '🧠',
  'color-names-ref':    '🎨',
  'lorem-ipsum-adv':    '📜',
  'grid-gen':           '▦',
  'meta-tags-adv':      '🏷️',

  // ── Text (was 🧹 on 4, 🖋️/🔍/🔄 on 3 each) ────────────────────────────────
  'word-counter-pro':    '🔢',
  'character-counter':   '🔡',
  'reading-time':        '⏱️',
  'word-frequency':      '📊',
  'text-statistics':     '📈',
  'unique-words':        '💎',
  'palindrome-checker':  '🔄',
  'anagram-checker':     '🔀',
  'text-sorter':         '🔤',
  'remove-duplicates':   '🧹',
  'remove-empty-lines':  '🚫',
  'trim-lines':          '✂️',
  'find-replace':        '🔍',
  'pig-latin':           '🐷',
  'text-randomizer':     '🎲',
  'url-slug':            '🔗',
  'remove-line-numbers': '#️⃣',
  'text-wrapper':        '📏',
  'text-unwrapper':      '📐',
  'text-truncator':      '🪒',
  'text-padder':         '⬜',
  'text-joiner':         '🪢',
  'text-splitter':       '🪓',
  'text-to-bullets':     '•',
  'bullets-to-text':     '📝',
  'text-to-numbered':    '🔟',
  'numbered-to-text':    '📄',
  'number-extractor':    '🧮',
  'url-extractor':       '🌐',
  'sentence-splitter':   '📑',
  'text-to-morse':       '📡',
  'morse-to-text':       '📻',
  'number-to-words':     '🔠',
  'words-to-number':     '💯',
};

// Falls back to the tool's inline icon, then the category motif, then a dot.
export function resolveIcon(tool, theme) {
  if (!tool) return '•';
  return TOOL_ICONS[tool.id] || tool.icon || theme?.motif || '•';
}
