import Head from 'next/head'

const C = {
  bg: '#06090F', surface: '#0D1117', border: 'rgba(255,255,255,0.08)',
  borderLight: 'rgba(255,255,255,0.05)', text: '#F1F5F9', muted: '#94A3B8',
  dim: '#64748B', navBg: 'rgba(6,9,15,0.92)',
}

const SECTIONS = [
  {
    title: 'General Information Only',
    content: `All content, calculators, generators and tools on ToolsRift (toolsrift.com) are provided for general informational and convenience purposes only. The information presented should not be relied upon as a substitute for professional advice.

While we strive to keep our tools accurate and up to date, ToolsRift makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability of the website, the tools or the results produced.`
  },
  {
    title: 'No Financial Advice',
    content: `The finance calculators on ToolsRift — including EMI, loan, tax, investment-return, SIP, compound interest and similar tools — are provided for educational and rough-estimation purposes only. They do not constitute financial, investment, tax, legal or accounting advice.

Specifically:

- Tax calculations may not reflect the latest tax laws, deductions, credits or local rules that apply to your specific situation
- Investment-return projections are based on the assumptions you enter and do not predict actual future returns
- Loan EMI calculations show approximate values; actual bank quotes may differ due to processing fees, prepayment terms and rate variations
- Currency conversions are based on indicative rates and should not be used for actual trades

For any financial decision involving real money — loans, investments, tax filings, business planning — consult a qualified financial advisor, chartered accountant or licensed professional in your jurisdiction. ToolsRift accepts no liability for financial decisions made based on calculator outputs.`
  },
  {
    title: 'No Medical or Health Advice',
    content: `The health calculators on ToolsRift — including BMI, TDEE, BMR, calorie intake, body fat, ideal weight, pregnancy due date, ovulation and similar tools — are provided for general informational purposes only. They do not constitute medical advice, diagnosis or treatment.

Specifically:

- BMI is a general screening tool and does not account for muscle mass, bone density, age, ethnicity or sex distribution
- TDEE and calorie calculations are estimates based on population averages and may not match your individual metabolism
- Pregnancy and ovulation calculators provide estimates only and should never replace consultation with a qualified obstetrician or fertility specialist
- Body composition estimates are approximations, not measurements

Always consult a qualified medical professional (doctor, registered dietitian, fertility specialist) for personal health decisions. ToolsRift accepts no liability for health decisions made based on calculator outputs.`
  },
  {
    title: 'No Legal Advice',
    content: `Documents generated by ToolsRift — including privacy policies, terms of service, cookie policies, NDAs, EULAs, refund policies and similar legal templates — are starting templates only. They are not a substitute for advice from a qualified attorney licensed in your jurisdiction.

Laws vary by country, state, industry and use case. A template that works for one business may be inadequate or actively wrong for another. Before publishing any legal document on a real business website or relying on it for a real transaction, have it reviewed and customized by a qualified attorney.

ToolsRift, its team and contributors accept no liability for legal consequences arising from the use of generated legal documents.`
  },
  {
    title: 'No Security Guarantees',
    content: `Our security and crypto tools — password generators, hash generators, JWT debugger, encryption helpers — are provided for general-purpose use and educational exploration. While we use industry-standard cryptographic primitives (Web Crypto API where applicable), no software can guarantee absolute security.

Specifically:

- Generated passwords are strong but their actual security depends on how you store and use them
- Hash algorithms like MD5 and SHA-1 are cryptographically broken; do not use them for new security-critical applications
- The JWT debugger decodes tokens but does not validate signatures, since that requires your secret key
- Sensitive credentials should not be casually pasted into any online tool — even ours

For security-critical applications (production password hashing, encryption at rest, key management), use audited libraries in your application code and consult a security professional.`
  },
  {
    title: 'External Links Disclaimer',
    content: `ToolsRift may contain links to external websites — for reference documentation, ad destinations, related resources or affiliate offers. We do not control these external sites and are not responsible for their content, privacy practices, accuracy or availability.

The presence of an external link does not imply endorsement of the linked site or its operators. We recommend reviewing the privacy policy and terms of any external site you visit through ToolsRift.`
  },
  {
    title: 'Advertising Disclaimer',
    content: `ToolsRift is supported by display advertising, primarily through Google AdSense and similar ad networks. The ads shown on our site are served by third-party ad networks and reflect their selection — not our endorsement.

We do not control which specific ads are shown, who the advertisers are, or what claims they make. Any transaction you enter into with an advertiser is solely between you and that advertiser. ToolsRift is not responsible for the products, services, claims or actions of any advertiser.

If you encounter an ad that violates Google\'s ad policies, please report it via the ad-info icon on the ad itself.`
  },
  {
    title: 'Accuracy of Tool Outputs',
    content: `While we make every effort to ensure that the tools on ToolsRift produce correct results, we do not guarantee accuracy in every case. Software has bugs; specifications change; edge cases exist. You should always verify important outputs through an independent source before relying on them.

If you find an inaccuracy in any of our tools, please report it via contact@toolsrift.com — we genuinely appreciate the help and respond to verified bugs quickly.`
  },
  {
    title: 'Use at Your Own Risk',
    content: `Your use of ToolsRift and any information or tools available on the site is solely at your own risk. ToolsRift, its team and contributors will not be liable for any loss or damage of any nature arising out of or related to use of the site.

In no event will ToolsRift be liable for any indirect, consequential, special or punitive damages — including lost profits, lost data, business interruption or personal injury — arising from your use of the tools.

For complete details on limitation of liability, please see our Terms of Service.`
  },
  {
    title: 'Contact',
    content: `If you have questions about this Disclaimer, please contact us:

Email: contact@toolsrift.com
Website: https://toolsrift.com
Location: Hyderabad, India`
  },
]

export default function Disclaimer() {
  return (
    <>
      <Head>
        <title>Disclaimer | ToolsRift</title>
        <meta name="description" content="ToolsRift Disclaimer. Our tools are for general informational use only. Not a substitute for professional financial, medical or legal advice." />
        <meta property="og:title" content="Disclaimer | ToolsRift" />
        <meta property="og:description" content="ToolsRift disclaimer covering financial, medical, legal and security limitations of our tools." />
        <meta property="og:url" content="https://toolsrift.com/disclaimer" />
        <meta property="og:site_name" content="ToolsRift" />
        <meta name="twitter:card" content="summary_large_image" />
        <link rel="canonical" href="https://toolsrift.com/disclaimer" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://toolsrift.com" },
            { "@type": "ListItem", "position": 2, "name": "Disclaimer" }
          ]
        })}} />
      </Head>

      <div style={{ background: C.bg, minHeight: '100vh', fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif", color: C.text }}>

        <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 24px', borderBottom: `1px solid ${C.borderLight}`, background: C.navBg, backdropFilter: 'blur(12px)', position: 'sticky', top: 0, zIndex: 100 }}>
          <a href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
            <img src="/logo.svg" alt="ToolsRift" style={{ height: 38 }} />
          </a>
          <a href="/" style={{ color: C.muted, textDecoration: 'none', fontSize: 14, fontWeight: 600, padding: '8px 16px', borderRadius: 8, border: `1px solid ${C.border}` }}>
            ← Back to Tools
          </a>
        </nav>

        <div style={{ maxWidth: 780, margin: '0 auto', padding: '48px 24px 80px' }}>

          <nav aria-label="Breadcrumb" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: C.dim, marginBottom: 36 }}>
            <a href="/" style={{ color: C.dim, textDecoration: 'none' }}>Home</a>
            <span>›</span>
            <span style={{ color: C.muted }}>Disclaimer</span>
          </nav>

          <div style={{ marginBottom: 48 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 20, padding: '5px 14px', fontSize: 12, color: '#FCA5A5', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 20 }}>
              Important Notice
            </div>
            <h1 style={{ fontSize: 'clamp(28px,4vw,42px)', fontWeight: 800, color: C.text, fontFamily: "'Sora', sans-serif", margin: '0 0 16px', lineHeight: 1.2 }}>
              Disclaimer
            </h1>
            <p style={{ fontSize: 15, color: C.muted, lineHeight: 1.7, margin: '0 0 12px' }}>
              ToolsRift offers free online tools for general informational and convenience purposes. The short version: our tools are useful starting points, but they are not a replacement for professional financial, medical, legal or security advice. Please read on for specifics.
            </p>
            <p style={{ fontSize: 13, color: C.dim }}>
              Last Updated: May 2026
            </p>
          </div>

          {SECTIONS.map((s, i) => (
            <div key={i} style={{ marginBottom: 36, paddingBottom: 36, borderBottom: `1px solid ${C.borderLight}` }}>
              <h2 style={{ fontSize: 18, fontWeight: 700, color: C.text, fontFamily: "'Sora', sans-serif", margin: '0 0 14px' }}>
                {s.title}
              </h2>
              <div style={{ fontSize: 14, color: C.muted, lineHeight: 1.85, whiteSpace: 'pre-line' }}>
                {s.content}
              </div>
            </div>
          ))}

        </div>

        <footer style={{ borderTop: `1px solid ${C.borderLight}`, padding: '28px 24px', textAlign: 'center', color: C.dim, fontSize: 13 }}>
          <div style={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap', gap: '6px 16px', marginBottom: 12 }}>
            {[['Home','/'],['About','/about'],['Contact','/contact'],['Privacy Policy','/privacy-policy'],['Terms','/terms'],['Disclaimer','/disclaimer'],['Cookies','/cookies']].map(([n,h]) => (
              <a key={h} href={h} style={{ color: C.dim, textDecoration: 'none' }}>{n}</a>
            ))}
          </div>
          <div>© 2026 ToolsRift · Free online tools, powered by ads.</div>
        </footer>
      </div>
    </>
  )
}
