import Head from 'next/head'

const C = {
  bg: '#06090F', surface: '#0D1117', border: 'rgba(255,255,255,0.08)',
  borderLight: 'rgba(255,255,255,0.05)', text: '#F1F5F9', muted: '#94A3B8',
  dim: '#64748B', navBg: 'rgba(6,9,15,0.92)',
}

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using ToolsRift (toolsrift.com) you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.

These terms apply to all visitors, users and others who access or use ToolsRift. We may update these terms at any time; continued use of the service after changes constitutes acceptance of the updated terms.`
  },
  {
    title: '2. Description of Service',
    content: `ToolsRift is a free online platform offering 669+ web-based tools across categories including text processing, image editing, PDF manipulation, calculators, code formatters, generators, and more.

All tools run entirely in your web browser using JavaScript and WebAssembly. We do not upload, store or process your files on our servers. The service is provided free of charge and is supported by display advertising.`
  },
  {
    title: '3. Permitted Use',
    content: `You may use ToolsRift for any lawful personal or commercial purpose, including:

- Processing your own files, text and data
- Generating content for use in personal, educational or commercial projects
- Integrating outputs into client deliverables, websites, apps and other works
- Sharing the platform with colleagues, students and friends

There is no usage license on outputs you produce — text you process, files you convert, passwords or images you generate are entirely yours to use.`
  },
  {
    title: '4. Prohibited Use',
    content: `You may not use ToolsRift to:

- Engage in any illegal activity or violate any local, state, national or international law
- Process or generate content that infringes intellectual property rights of others
- Generate or distribute malware, phishing pages or fraudulent content
- Attempt to disrupt, overload or impair the service or supporting infrastructure
- Scrape, automate or programmatically use the tools beyond reasonable personal volume
- Attempt to reverse engineer, decompile or extract source code for commercial redistribution
- Use any automated means to access the service without our written permission

We reserve the right to block access to users who violate these terms.`
  },
  {
    title: '5. Intellectual Property',
    content: `The ToolsRift name, logo, website design, code and curated content are the property of ToolsRift. You may not copy, modify, distribute or create derivative works of ToolsRift\'s proprietary elements without permission.

Outputs generated by the tools (formatted text, converted files, generated passwords or designs) are yours. You retain full ownership of any content you create using the tools.`
  },
  {
    title: '6. Privacy & Data',
    content: `ToolsRift is designed with privacy as a core principle. All file processing happens in your browser — files are never uploaded to our servers. We collect minimal anonymized analytics and use cookies for advertising support.

Detailed information about data collection is available in our Privacy Policy and Cookie Policy.`
  },
  {
    title: '7. Advertising',
    content: `ToolsRift is a free service supported by display advertising, primarily through Google AdSense. By using the service you acknowledge that ads will be shown on pages you visit.

We work to keep ads non-intrusive and relevant. We do not control the specific ads shown or the advertisers that bid through ad networks. If you encounter an ad that violates Google\'s advertising policies, please report it via the report-ad link on the ad itself.

ToolsRift is not responsible for the content of third-party advertisements or any transactions you enter into with advertisers.`
  },
  {
    title: '8. Disclaimer of Warranties',
    content: `ToolsRift is provided "as is" and "as available" without warranties of any kind, either express or implied. To the maximum extent permitted by law, we disclaim all warranties including:

- Merchantability and fitness for a particular purpose
- Non-infringement
- Accuracy, reliability or completeness of any tool output
- Uninterrupted, error-free or virus-free service

The tools are intended for general use. Results should be verified for any business-critical, legal, medical, financial or safety-critical purpose. See our Disclaimer page for specific disclaimers regarding finance and health calculators.`
  },
  {
    title: '9. Limitation of Liability',
    content: `To the maximum extent permitted by law, ToolsRift and its team will not be liable for any indirect, incidental, special, consequential or punitive damages arising from your use of (or inability to use) the service, including but not limited to:

- Loss of profits, revenue, data or business opportunities
- Errors in outputs of the tools
- Decisions made based on calculator results
- Service interruptions or downtime
- Acts of third-party advertisers or services

Your sole remedy for dissatisfaction with the service is to stop using it.`
  },
  {
    title: '10. Indemnification',
    content: `You agree to indemnify and hold harmless ToolsRift and its team from any claims, damages, losses, liabilities and expenses (including legal fees) arising from:

- Your use of the service
- Your violation of these terms
- Your violation of any law or rights of any third party
- Content you process or generate using the tools

This indemnification obligation will survive termination of these terms and your use of the service.`
  },
  {
    title: '11. Modifications to Service',
    content: `We reserve the right to modify, suspend or discontinue any part of the service at any time without notice. We may add, remove or change tools as the platform evolves.

We are not liable to you or any third party for any modification, suspension or discontinuation of the service.`
  },
  {
    title: '12. Termination',
    content: `We may terminate or restrict your access to the service at any time without notice if you violate these terms. You may stop using the service at any time without notice.

Provisions that by their nature should survive termination — including intellectual property, disclaimers, limitation of liability and indemnification — will continue to apply.`
  },
  {
    title: '13. Governing Law',
    content: `These terms are governed by the laws of India without regard to conflict-of-law principles. Any dispute arising from these terms or use of the service will be subject to the exclusive jurisdiction of the courts of Hyderabad, Telangana, India.`
  },
  {
    title: '14. Contact',
    content: `For questions about these Terms of Service, please contact:

Email: contact@toolsrift.com
Website: https://toolsrift.com
Location: Hyderabad, India

We aim to respond to all enquiries within 2-3 business days.`
  },
]

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service | ToolsRift</title>
        <meta name="description" content="ToolsRift Terms of Service. Read the terms governing use of our free online tools platform — permitted use, disclaimers and limitations." />
        <meta property="og:title" content="Terms of Service | ToolsRift" />
        <meta property="og:description" content="Terms of service for ToolsRift — permitted use, prohibited use, disclaimers and limitations of liability." />
        <meta property="og:url" content="https://toolsrift.com/terms" />
        <meta property="og:site_name" content="ToolsRift" />
        <meta name="twitter:card" content="summary_large_image" />
        <link rel="canonical" href="https://toolsrift.com/terms" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://toolsrift.com" },
            { "@type": "ListItem", "position": 2, "name": "Terms of Service" }
          ]
        })}} />
      </Head>

      <div style={{ background: C.bg, minHeight: '100vh', fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif", color: C.text }}>

        <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 24px', borderBottom: `1px solid ${C.borderLight}`, background: C.navBg, backdropFilter: 'blur(12px)', position: 'sticky', top: 0, zIndex: 100 }}>
          <a href="/" style={{ display: 'flex', alignItems: 'center', textDecoration: 'none' }}>
            <img src="/logo.svg" alt="ToolsRift" style={{ height: 38 }} />
          </a>
          <a href="/" style={{ color: C.muted, textDecoration: 'none', fontSize: 14, fontWeight: 600, padding: '8px 16px', borderRadius: 8, border: `1px solid ${C.border}` }}>
            ← Back to Tools
          </a>
        </nav>

        <div style={{ maxWidth: 780, margin: '0 auto', padding: '48px 24px 80px' }}>

          <nav aria-label="Breadcrumb" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: C.dim, marginBottom: 36 }}>
            <a href="/" style={{ color: C.dim, textDecoration: 'none' }}>Home</a>
            <span>›</span>
            <span style={{ color: C.muted }}>Terms of Service</span>
          </nav>

          <div style={{ marginBottom: 48 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.2)', borderRadius: 20, padding: '5px 14px', fontSize: 12, color: '#FCD34D', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 20 }}>
              Legal Document
            </div>
            <h1 style={{ fontSize: 'clamp(28px,4vw,42px)', fontWeight: 800, color: C.text, fontFamily: "'Sora', sans-serif", margin: '0 0 16px', lineHeight: 1.2 }}>
              Terms of Service
            </h1>
            <p style={{ fontSize: 15, color: C.muted, lineHeight: 1.7, margin: '0 0 12px' }}>
              These terms govern your use of ToolsRift. The short version: use the tools for any lawful purpose, do not abuse the service, and understand that we provide everything "as is" without warranty. The full terms are below.
            </p>
            <p style={{ fontSize: 13, color: C.dim }}>
              Last Updated: May 2026 &nbsp;·&nbsp; Effective Date: April 2026
            </p>
          </div>

          {SECTIONS.map((s, i) => (
            <div key={i} style={{ marginBottom: 36, paddingBottom: 36, borderBottom: `1px solid ${C.borderLight}` }}>
              <h2 style={{ fontSize: 18, fontWeight: 700, color: C.text, fontFamily: "'Sora', sans-serif", margin: '0 0 14px' }}>
                {s.title}
              </h2>
              <div style={{ fontSize: 14, color: C.muted, lineHeight: 1.85, whiteSpace: 'pre-line' }}>
                {s.content}
              </div>
            </div>
          ))}

        </div>

        <footer style={{ borderTop: `1px solid ${C.borderLight}`, padding: '28px 24px', textAlign: 'center', color: C.dim, fontSize: 13 }}>
          <div style={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap', gap: '6px 16px', marginBottom: 12 }}>
            {[['Home','/'],['About','/about'],['Contact','/contact'],['Privacy Policy','/privacy-policy'],['Terms','/terms'],['Disclaimer','/disclaimer'],['Cookies','/cookies']].map(([n,h]) => (
              <a key={h} href={h} style={{ color: C.dim, textDecoration: 'none' }}>{n}</a>
            ))}
          </div>
          <div>© 2026 ToolsRift · Free online tools, powered by ads.</div>
        </footer>
      </div>
    </>
  )
}
