#!/usr/bin/env python3
"""
extract-tools.py — Regenerates lib/toolRegistry.js from category components.
Run whenever you add/remove tools:  python3 scripts/extract-tools.py
Then regenerate the sitemap:        node scripts/generate-sitemap.js
"""
import re, json, os
os.chdir(os.path.join(os.path.dirname(__file__), '..'))

MAP = {
 'business':'toolsrift-business','colors':'toolsrift-colors','converters2':'toolsrift-converters2',
 'css':'toolsrift-css','devgen':'toolsrift-gen-devconfig','devtools':'toolsrift-devtools',
 'encoders':'toolsrift-encoders','encoding':'toolsrift-encoding','everyday':'toolsrift-everyday','fancy':'toolsrift-fancy',
 'financecalc':'toolsrift-calc-finance','formatters':'toolsrift-formatters',
 'generators':'toolsrift-gen-security','generators2':'toolsrift-gen-content','hash':'toolsrift-hash',
 'html':'toolsrift-html','images':'toolsrift-images','js':'toolsrift-js','json':'toolsrift-json',
 'mathcalc':'toolsrift-calc-math','pdf':'toolsrift-pdf','text':'toolsrift-text','units':'toolsrift-units',
}

cc = open('lib/categoryContent.js', encoding='utf-8').read()
names = {m.group(1): m.group(2) for m in
         re.finditer(r"(\w+):\s*\{[^{}]*?categoryName:\s*['\"]([^'\"]+)['\"]", cc)}

def tools_array(src):
    i = src.find('const TOOLS'); i = src.find('[', i)
    depth, j = 0, i
    while j < len(src):
        if src[j] == '[': depth += 1
        elif src[j] == ']':
            depth -= 1
            if depth == 0: break
        j += 1
    return src[i:j+1]

def objects(arr):
    out, depth, start = [], 0, None
    for k, ch in enumerate(arr):
        if ch == '{':
            if depth == 0: start = k
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0 and start is not None:
                o = arr[start:k+1]
                i = re.search(r"\bid:\s*['\"]([^'\"]+)['\"]", o)
                n = re.search(r"\bname:\s*['\"]([^'\"]*)['\"]", o)
                d = re.search(r"\bdesc:\s*['\"]([^'\"]*)['\"]", o)
                if i and n:
                    out.append({'id': i.group(1), 'name': n.group(1),
                                'desc': d.group(1) if d else ''})
    return out

registry, total = {}, 0
for slug, comp in MAP.items():
    src = open(f'components/{comp}.jsx', encoding='utf-8').read()
    seen, unique = set(), []
    for t in objects(tools_array(src)):
        if t['id'] not in seen and re.fullmatch(r'[a-z0-9-]+', t['id']):
            seen.add(t['id']); unique.append(t)
    registry[slug] = {'name': names.get(slug, slug.title()+' Tools'), 'tools': unique}
    total += len(unique)
    print(f"{slug:14s} {len(unique):4d} tools")

print(f"TOTAL: {total} tools")
out = ("// AUTO-GENERATED by scripts/extract-tools.py — do not edit by hand.\n"
       "// Regenerate whenever tools are added/removed in category components.\n"
       "const TOOL_REGISTRY = " + json.dumps(registry, indent=2, ensure_ascii=False) + ";\n\n"
       "export default TOOL_REGISTRY;\n")
open('lib/toolRegistry.js', 'w', encoding='utf-8').write(out)
print("lib/toolRegistry.js written")
